version: "3"

# Definir servicios
services:
  litestratmodeller:
    restart: always
    image: cuentaDockerHub
    #aqui falta linkear la imagen
    environment:
      - VIRTUAL_HOST=litestratmodeller.informatica.uv.cl
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
# Definir redes
#networks:
#  default:
#    external:
#      name: nginx-proxy
# Define networks
networks:
  nginx-proxy:
    external: true
